server:
  port: 8080
spring:
  profiles:
    active: dev

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boardgames
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  config:
    activate:
      on-profile: dev

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boardgames_v2_prod
    username: root
    password: vakula
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  config:
    activate:
      on-profile: prod
