server:
  port: 8080
spring:
  profiles:
    active: prod

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boardgames_v2
    username: root
    password: vakula
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  config:
    activate:
      on-profile: dev

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boardgames_prod
    username: root
    password: vakula
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'
  config:
    activate:
      on-profile: prod
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
file:
  upload-dir: "/Vale/boardgames-images"
